---
- name: Update and configure servers
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - curl
          - wget
          - vim
        state: present

- name: Install K3s on master node
  hosts: masterpi
  become: yes
  tasks:
    - name: Download K3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0700'

    - name: Install K3s on master node
      shell: |
        INSTALL_K3S_EXEC="server --cluster-init" /tmp/k3s_install.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Get node token
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

- name: Install K3s on worker nodes
  hosts: node1pi,node2pi,node3pi
  become: yes
  vars:
    master_ip: "{{ hostvars['masterpi']['ansible_host'] }}"
    node_token: "{{ hostvars['masterpi']['node_token']['stdout'] }}"
  tasks:
    - name: Download K3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0700'

    - name: Install K3s on worker nodes
      shell: |
        K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ node_token }} /tmp/k3s_install.sh
      args:
        creates: /usr/local/bin/k3s

- name: Configure high availability
  hosts: node1pi,node2pi
  become: yes
  vars:
    master_ip: "{{ hostvars['masterpi']['ansible_host'] }}"
    node_token: "{{ hostvars['masterpi']['node_token']['stdout'] }}"
  tasks:
    - name: Install K3s as additional server nodes
      shell: |
        K3S_TOKEN={{ node_token }} INSTALL_K3S_EXEC="server --server https://{{ master_ip }}:6443" /tmp/k3s_install.sh
      args:
        creates: /usr/local/bin/k3s
